spring.application.name=makemytrip
server.port=8080
spring.data.mongodb.uri="mongodb+srv://User:<user1234>@makemytrip.nxczkdb.mongodb.net/"
spring.data.mongodb.database=makemytrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
